import type { Metadata } from 'next';
import { course, outcomes } from '@/lib/course-data';

export const metadata: Metadata = { title: 'Course Overview', description: 'Official DATA301 course facts, outcomes, pedagogy, and instructor information.' };

export default function AboutPage() {
  return (
    <main id="main-content">
      <section className="page-hero page-hero--course"><div className="shell page-hero__grid"><div><span className="eyebrow">{course.code} · Course overview</span><h1>{course.title}</h1><p>{course.description}</p></div><div className="course-fact-grid"><div><span>Program</span><strong>{course.program}</strong></div><div><span>Semester</span><strong>{course.semester}</strong></div><div><span>Credits</span><strong>{course.credits}</strong></div><div><span>LTP</span><strong>{course.ltp}</strong></div><div><span>Duration</span><strong>{course.durationWeeks} weeks</strong></div><div><span>Prerequisite</span><strong>MATH301</strong></div></div></div></section>
      <section className="section shell about-grid"><div><span className="eyebrow">Course outcomes</span><h2>What successful completion should enable.</h2><div className="outcome-list">{outcomes.map((outcome) => <article key={outcome.code}><span>{outcome.code}</span><p>{outcome.description}</p><b>{outcome.level}</b></article>)}</div></div><aside className="instructor-card"><span className="eyebrow">Design contract</span><h2>Inspectable before impressive.</h2><p>The studio keeps small algorithm implementations, deterministic datasets, and explicit definitions close to the visual explanation.</p><div><span>Every laboratory should expose</span><ul><li>the model or metric being computed</li><li>the parameter that changes behavior</li><li>the failure or boundary case</li></ul></div><div><span>Every experiment should retain</span><ul><li>a baseline and metric</li><li>data-split and leakage discipline</li><li>reproducible configuration</li></ul></div><small>The public edition is an independent reference implementation, not an official institutional publication.</small></aside></section>
      <section className="section section--paper"><div className="shell pedagogy-grid"><div><span className="eyebrow">Pedagogy</span><h2>Lecture, practice, problem solving, and evidence.</h2><p>The detailed plan describes lectures, presentations, hands-on labs, case studies, assignments, datasets, problem-based learning, and structured self-learning.</p></div><div className="pedagogy-cards"><article><span>01</span><h3>Understand</h3><p>Build conceptual and mathematical foundations through lectures and visual explanations.</p></article><article><span>02</span><h3>Implement</h3><p>Use Python, SciPy, and Scikit-learn in paired practice sessions.</p></article><article><span>03</span><h3>Evaluate</h3><p>Choose appropriate metrics and inspect errors rather than reporting one score.</p></article><article><span>04</span><h3>Apply</h3><p>Integrate the course through a team project, demonstration, report, and viva.</p></article></div></div></section>
    </main>
  );
}
