import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { Icon } from '@/components/ui/Icon';
import { platform } from '@/lib/platform';

export const metadata: Metadata = { title: 'About the Platform', description: 'About DATA301 Machine Learning Studio, its academic setting, purpose, and development.' };

export default function AboutPage() {
  return <main id="main-content" className="d6-page d6-about">
    <section className="d6-about-hero"><div className="d6-shell"><p className="d6-eyebrow">DATA301 · Vidyashilp University</p><h1>Learning happens in a place.<em>It should feel like one.</em></h1><p>DATA301 ML Studio is a course environment designed around seeing, changing, explaining and implementing machine-learning ideas.</p></div></section>
    <figure className="d6-about-photo"><Image src="/campus/vu-campus-hero.webp" alt="Vidyashilp University campus" fill priority sizes="100vw"/><figcaption><span>Vidyashilp University</span><span>School of Engineering &amp; Technology</span></figcaption></figure>
    <section className="d6-about-setting"><div><p className="d6-eyebrow">The setting</p><h2>A university course with a digital front door.</h2></div><div><p>DATA301 sits within the School of Engineering &amp; Technology. The platform carries that context into the interface: a real course sequence, real laboratories, published material, instructor administration and a visible connection to campus.</p><Link href="/course">Explore the course <Icon name="arrow" size={15}/></Link></div></section>
    <section className="d6-about-philosophy"><div className="d6-shell d6-about-philosophy__grid"><div><p className="d6-eyebrow d6-eyebrow--light">Learning philosophy</p><h2>See it.<br/>Change it.<br/>Explain it.</h2></div><div className="d6-about-principles">{[['01','See','Visualize boundaries, residuals, margins, clusters and metrics.'],['02','Change','Manipulate parameters and observe the consequence of each decision.'],['03','Explain','Connect model behaviour to mathematical and practical reasoning.'],['04','Implement','Carry the idea into Python, evaluation, experiments and projects.']].map(([n,t,p])=><article className="d6-about-principle" key={n}><span>{n}</span><h3>{t}</h3><p>{p}</p></article>)}</div></div></section>
    <section className="d6-about-collage"><div className="d6-shell"><div className="d6-about-collage__head"><div><p className="d6-eyebrow">Around the university</p><h2>One course.<br/>One real campus.</h2></div><p>The photographic layer is intentionally secondary to the academic experience: place gives the product identity, while the course remains the subject.</p></div><div className="d6-about-collage__grid"><figure className="d6-about-collage__main"><Image src="/campus/vu-campus-building.webp" alt="Vidyashilp University academic buildings" fill sizes="(max-width: 760px) 100vw, 67vw"/><figcaption>Academic buildings</figcaption></figure><div className="d6-about-collage__stack"><figure><Image src="/campus/vu-campus-detail.webp" alt="Vidyashilp University architecture" fill sizes="(max-width: 760px) 100vw, 33vw"/><figcaption>Architecture</figcaption></figure><figure><Image src="/campus/vu-campus-atmosphere.webp" alt="Vidyashilp University campus atmosphere" fill sizes="(max-width: 760px) 100vw, 33vw"/><figcaption>Campus atmosphere</figcaption></figure></div></div></div></section>
    <section className="d6-about-colophon"><div className="d6-shell d6-about-colophon__grid"><div><p className="d6-eyebrow">Academic context</p><h2>DATA301<br/>Machine Learning</h2><p>Course instruction and academic materials by {platform.instructor.name}, Vidyashilp University.</p><Link href={platform.universityUrl} target="_blank" rel="noreferrer">Vidyashilp University <Icon name="external" size={14}/></Link></div><div><p className="d6-eyebrow">Platform development</p><h2>{platform.developer.name}</h2><p>{platform.developer.role}. Product architecture, interface design, interactive laboratories, backend integration and release engineering.</p><Link href={platform.developer.repository} target="_blank" rel="noreferrer">Source repository <Icon name="github" size={15}/></Link></div></div></section>
  </main>;
}
